# Generated by Django 5.0 on 2023-12-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='download_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default='file from <django.db.models.fields.related.ForeignKey>', max_length=64),
        ),
    ]
