# Generated by Django 4.2.5 on 2023-12-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0003_remove_file_download_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='author',
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(default='unnamed file', max_length=64),
        ),
    ]
